INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flatiron", "Coding", 1500, "3/1/18", "3/31/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Summer Flights", "Travel", 635, "3/1/18", "3/31/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Purim Costume", "Holidays", 50, "3/1/18", "3/31/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Soup Kitchen", "Homeless", 250, "3/1/18", "3/31/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Eruv 5k", "Community", 1000, "3/1/18", "3/31/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("CAPS Sessions", "Mental Health", 75, "3/1/18", "3/31/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wig Making", "Cancer Survivors", 1000, "2/1/17", "2/28/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dog Harnesses", "Blind & Deaf", 500, "2/1/17", "2/28/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Musical Instruments", "Developmental Disabilities", 315, "2/1/17", "2/28/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("PTSD Counseling", "Military", 80, "2/1/17", "2/28/18");

INSERT INTO users (name, age) VALUES ("Alexis Dorn", 26);
INSERT INTO users (name, age) VALUES ("Jacob Dorn", 27);
INSERT INTO users (name, age) VALUES ("Claire Dorn", 24);
INSERT INTO users (name, age) VALUES ("Patrick Dorn", 51);
INSERT INTO users (name, age) VALUES ("Abby Dorn", 50);
INSERT INTO users (name, age) VALUES ("Bill Dorn", 85);
INSERT INTO users (name, age) VALUES ("Steve Ulrich", 49);
INSERT INTO users (name, age) VALUES ("Amy Ulrich", 45);
INSERT INTO users (name, age) VALUES ("Chris Johnson", 38);
INSERT INTO users (name, age) VALUES ("Jim Ulrich", 84);
INSERT INTO users (name, age) VALUES ("Alisha Bowman", 27);
INSERT INTO users (name, age) VALUES ("Kayla Payne", 27);
INSERT INTO users (name, age) VALUES ("Jason Banning", 27);
INSERT INTO users (name, age) VALUES ("Morgan Johnson", 26);
INSERT INTO users (name, age) VALUES ("Casey Ulrich", 27);
INSERT INTO users (name, age) VALUES ("Taylor Ulrich", 24);
INSERT INTO users (name, age) VALUES ("Kyle Ulrich", 31);
INSERT INTO users (name, age) VALUES ("Sean Pinnow", 32);
INSERT INTO users (name, age) VALUES ("Brady Ulrich", 19);
INSERT INTO users (name, age) VALUES ("Jaren Ulrich", 22);

INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);